source 'https://github.com/CocoaPods/Specs.git'

workspace 'RATreeViewExamples.xcworkspace'
platform :ios, '5.0'
use_frameworks!

target 'RATreeViewBasicExample' do
  pod 'RATreeView', :path => '../RATreeView.podspec'
end

target 'RATreeViewBasicExampleSwift' do
  pod 'RATreeView', :path => '../RATreeView.podspec'
end
